services:
  gateway-service:
    build: ./api-gateway
    container_name: apigateway-service
    ports:
      - "5000:5000"
    env_file:
      - ./api-gateway/config.env
    networks:
      - app-network
    depends_on:
      - user-service
      - publisher-service
      - consumer-service

  user-service:
    build: ./user
    container_name: user-service
    ports:
      - "3000:3000"
    env_file:
      - ./user/config.env
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy

  publisher-service:
    build: ./publisher
    container_name: publisher-service
    ports:
      - "3001:3001"
    env_file:
      - ./publisher/config.env
    networks:
      - app-network
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer-service:
    build: ./consumer
    container_name: consumer-service
    ports:
      - "3002:3002"
    env_file:
      - ./consumer/config.env
    networks:
      - app-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
