version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vehicle-tracker-backend
    ports:
      - '3000:3000'
    env_file:
      - ./config.env
    networks:
      - app-network
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    container_name: vehicle-tracker-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis
    container_name: vehicle-tracker-redis
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
